# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ES-CE-LR-INT SINIDEVASIA(9ca95e44-6fce-4ef1-9ccc-9726db766ea7)'
    subscriptionId: '9ca95e44-6fce-4ef1-9ccc-9726db766ea7'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Test-ReleasePipeline'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/VNet/VNet-Template.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/VNet/VNet-Parameter.json'
    deploymentMode: 'Incremental'