# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"

stages:
  - stage: test
    jobs:
      - job: 'validateandtest'
        pool:
          vmimage: windows-latest
        steps:

stages:
  - stage: test
    jobs:
      - job: 'validateandtest'
        pool:
          vmimage: windows-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'ES-CE-LR-INT SINIDEVASIA(9ca95e44-6fce-4ef1-9ccc-9726db766ea7)'
            subscriptionId: '9ca95e44-6fce-4ef1-9ccc-9726db766ea7'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'AzureAutomate'
            location: 'East US'
            templateLocation: 'Linked artifact'
            csmFile: 'CreateVNetwithmultiplesubnets-TemplateFile.json'
            csmParametersFile: 'CreateVNetwithmultiplesubnets-ParameterFile.JSON'
            deploymentMode: 'Incremental'