trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: ''
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ES-CE-LR-INT SINIDEVASIA(9ca95e44-6fce-4ef1-9ccc-9726db766ea7)'
    subscriptionId: '9ca95e44-6fce-4ef1-9ccc-9726db766ea7'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Test-Pipeline'
    location: 'EastUS'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/VNet-Template.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/VNet-Parameter.json'
    deploymentMode: 'Incremental'